Update start_stop_ecs_service.yml

diff --git a/.github/workflows/start_stop_ecs_service.yml b/.github/workflows/start_stop_ecs_service.yml
--- a/.github/workflows/start_stop_ecs_service.yml
+++ b/.github/workflows/start_stop_ecs_service.yml
@@ -43,6 +43,10 @@ jobs:
           status=$(aws ecs describe-services --cluster ${{ github.event.inputs.aws-account}}-${{ github.event.inputs.application-name}}-${{ github.event.inputs.environment }} --services ${{ github.event.inputs.aws-account}}-${{ github.event.inputs.application-name}}-${{ github.event.inputs.environment }} --query 'services[0].status')
           echo "Service_Status=$status" >> $GITHUB_ENV
           echo "Service status: $status"
+          if [[ $status == 'ServiceNotFound' ]]; then
+            echo "::error::ECS service not found: $service_name"
+            exit 1
+          fi
 
       - name: Get running task count
         id: task_count
